namespace SecureTPMVault;

/// <summary>
/// Contains static informational text resources, specifically for critical user warnings.
/// </summary>
internal static class VaultInfo
{
    /// <summary>
    /// The content of the 'READ_ME_CRITICAL.txt' file placed alongside the master key.
    /// Explains the technical importance of the user_master.dat file.
    /// </summary>
    public const string MasterKeyWarning =
        """
        ================================================================================
        [CRITICAL SYSTEM WARNING] DO NOT DELETE OR MODIFY THIS FOLDER
        ================================================================================

        FILE: user_master.dat
        TYPE: High-Entropy Cryptographic Identity (32-byte CSPRNG)

        TECHNICAL EXPLANATION:
        This file contains the machine-specific and user-specific cryptographic seed 
        required to derive the encryption keys for your secured files (.tpmPassword).

        1. DPAPI PROTECTION: 
           This file itself is encrypted using Windows DPAPI (Data Protection API). 
           It is bound to your specific Windows User Account and this physical machine.
           Copying this file to another computer WILL NOT WORK. The decryption will fail.

        2. NO BACKDOOR:
           The encryption algorithm (AES-256 via SHA-256 Key Derivation) creates a 
           mathematical dependency on this file. If this file is deleted, lost, or 
           corrupted, ALL your encrypted .tpmPassword files become mathematically 
           impossible to decrypt. There is no "Forgot Password" mechanism.

        3. WHY IS THIS HERE?
           To provide maximum security without requiring you to remember a master password,
           we leverage the OS's security subsystem. This folder acts as your 
           digital keychain.

        ACTION REQUIRED:
        - Do not delete this file.
        - Do not rename this folder.
        - If you backup your computer, backup this folder, but remember: 
          restoring it to a different Windows installation usually invalidates the key 
          due to DPAPI machine-binding constraints.

        generated by: TPM Secure Vault Application
        ================================================================================
        """;
}